### ISSUE TITLE
problem in data

### ISSUE THREAD

**Issue by AbdallahQoutbAli** [Bastian/Abstractive-Summarization-of-Meetings#2]
Hellow 
i'm tring to add my meeting text to but the result not good in file predit-predctions.txt 
before add text must run Meeting-Parser. ?

**Comment by Bastian** [comment]
Hi, thank your for your interest in the repository.

What data did you use to train the network and how similar is it to the data you are trying to predict?
Unfortunately the network is not very good at generalizing. These are my results on the AMI and ICSI meeting corpora:
![image](https://user-images.githubusercontent.com/5033001/81838016-de1dd300-9545-11ea-8cdc-d0659403bdad.png)
with
* **`AAA`** -> Trained on AMI and tested on AMI
* **`III`** -> Trained on ICSI and tested on ICSI
* **`AAI`** -> Trained on AMI and tested on ICSI

You can see, that the results on the cross-corpus test (`AAI`) are significantly worse. Do not expect too much from the network, as this was mainly an experiment.

More details are described in chapter 5 (Experiments) and chapter 7 (Summary and Conclusion) of my bachelor's thesis: https://github.com/Bastian/bachelors-thesis/releases/download/submission/thesis-colored-links.pdf

I hope this helps! :slightly_smiling_face:

**Comment by AbdallahQoutbAli** [comment]
Thank very much for replay
I'm training model using your files in  data folder after 80 epoch give me Good output in Your file predict. 
but not Good in my text Link :
 https://drive.google.com/file/d/1NPI7gjRVzirHjvgv9fX1QIC3uWCmoJ85/view?usp=sharing
the text content interview between to person, the ouptut using model speech to text  in my graduation project 
Now I will read chapters ,training in AMI  data, and test text again

**Comment by AbdallahQoutbAli** [comment]
Hello
Can you upload pre-traind model ?

**Comment by Bastian** [comment]
Sorry for the late response, I somehow missed your comment.
If you still need it, here you go: Here's my output folder after training on the AMI dataset: https://drive.google.com/drive/folders/1XD694hafdMFirCRitwMhkVFchxFJvCGq?usp=sharing :)
