### ISSUE TITLE
link to model

### ISSUE THREAD

**Issue by manthan3105** [Bastian/Abstractive-Summarization-of-Meetings#3]
My hardware doesnt support training this model. Google colab is giving memory issues. Can anyone pls send a drive link with model or anything.

**Comment by Bastian** [comment]
Here's my output folder after training on the AMI dataset: https://drive.google.com/drive/folders/1XD694hafdMFirCRitwMhkVFchxFJvCGq?usp=sharing

**Comment by manthan3105** [comment]
Hi,
Thank you so much, Bastian.
Warm regards
Manthan
